# Generated by Django 3.2.4 on 2021-06-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_article_comment'),
        ('account', '0002_auto_20210626_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feeds',
            field=models.ManyToManyField(blank=True, db_table='user_feeds', related_name='feeds', to='feed.Feed', verbose_name='Feeds'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_articles',
            field=models.ManyToManyField(blank=True, db_table='liked_articles', related_name='user_liked', to='feed.Article', verbose_name='Like'),
        ),
        migrations.AlterField(
            model_name='user',
            name='read_articles',
            field=models.ManyToManyField(blank=True, db_table='read_articles', related_name='user_read', to='feed.Article', verbose_name='Read'),
        ),
    ]
