# Generated by Django 3.2.4 on 2021-06-26 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Author')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Pub Date')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='feed.feed', verbose_name='Feed')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.article', verbose_name='Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comment')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
