# Generated by Django 3.2.4 on 2021-06-27 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_article_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='feed.feed', verbose_name='Feed'),
        ),
    ]
